config/routes.rb
Rails.application.routes.draw do
  

  resources :roles

  devise_for :users
  root 'welcome#home'
  get 'welcome', to: 'welcome#index'
  get 'settings', to: 'settings#index'
  
  resources :employees

  resources :guardians

  resources :students
  
  resources :users
  
  resources :exam_categories
  
  resources :periods
  
  resources :groups do
    resources :attendances
    resources :attendance_registers
  end

  resources :courses do 
    resources :curriculums
    resources :chapters
    resources :lessons
    resources :exam_categories
    resources :exams do 
        resources :grades
    end
  end
  
  resources :course_categories

  
  

end

app/models/course_category.rb
class CourseCategory < ActiveRecord::Base
  has_many :courses
end

app/controllers/course_categories_controller.rb
class CourseCategoriesController < ApplicationController
  before_action :set_course_category, only: [:show, :edit, :update, :destroy]

  # GET /course_categories
  # GET /course_categories.json
  def index
    @course_categories = CourseCategory.all
  end

  # GET /course_categories/1
  # GET /course_categories/1.json
  def show
  end

  # GET /course_categories/new
  def new
    @course_category = CourseCategory.new
  end

  # GET /course_categories/1/edit
  def edit
  end

  # POST /course_categories
  # POST /course_categories.json
  def create
    @course_category = CourseCategory.new(course_category_params)

    respond_to do |format|
      if @course_category.save
        format.html { redirect_to @course_category, notice: 'Course category was successfully created.' }
        format.json { render :show, status: :created, location: @course_category }
      else
        format.html { render :new }
        format.json { render json: @course_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /course_categories/1
  # PATCH/PUT /course_categories/1.json
  def update
    respond_to do |format|
      if @course_category.update(course_category_params)
        format.html { redirect_to @course_category, notice: 'Course category was successfully updated.' }
        format.json { render :show, status: :ok, location: @course_category }
      else
        format.html { render :edit }
        format.json { render json: @course_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /course_categories/1
  # DELETE /course_categories/1.json
  def destroy
    @course_category.destroy
    respond_to do |format|
      format.html { redirect_to course_categories_url, notice: 'Course category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course_category
      @course_category = CourseCategory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def course_category_params
      params.require(:course_category).permit(:cc_name)
    end
end

app/helpers/course_categories_helper.rb
module CourseCategoriesHelper
end

app/views/course_categories/_form.html.erb
<%= form_for(@course_category) do |f| %>
  <% if @course_category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@course_category.errors.count, "error") %> prohibited this course_category from being saved:</h2>

      <ul>
      <% @course_category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <fieldset>
    
      <div class="row">
        <div class="medium-6 columns">
          <div class="field">
            <%= f.label :category_title %><br>
            <%= f.text_field :cc_name %>
          </div>
        </div>
    </div>
  </fieldset>

  <div class="actions">
    <%= f.submit class: "button success radius" %> &nbsp;&nbsp;
    <%= link_to 'Cancel', @course_category, class: "button secondary radius" %>
  </div>
<% end %>

app/views/course_categories/edit.html.erb
<% provide(:title, 'Editing Course Category') %>

<div class="page-title">
  <h1><%= 'Editing Course Category' %></h1>
</div>

<%= render 'form' %>

app/views/course_categories/index.html.erb
<% provide(:title, 'Course Categories') %>

<div class="page-title">
  <h1><%= 'Course Categories' %></h1>
</div>

<table class="responsive">
  <thead>
    <tr>
      <th>Categories</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @course_categories.each do |course_category| %>
      <tr>
        <td><%= link_to course_category.cc_name, course_category %></td>
        <td><%= link_to 'Edit', edit_course_category_path(course_category) %></td>
        <td><%= link_to 'Destroy', course_category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Create a new category', new_course_category_path, class: "button radius" %> &nbsp; &nbsp;
<%= link_to 'Back', settings_url, class: 'button secondary radius' %>

app/views/course_categories/new.html.erb
<% provide(:title, 'New Course Category') %>

<div class="page-title">
  <h1><%= 'New Course Category' %></h1>
</div>

<%= render 'form' %>

<%= link_to 'Back', course_categories_path %>

app/views/course_categories/show.html.erb
<% provide(:title, @course_category.cc_name) %>

<div class="page-title clearfix">
  <h1><%= @course_category.cc_name %> <span class="right"><%= link_to 'Edit', edit_course_category_path(@course_category) %> | <%= link_to 'Back', course_categories_path %></span></h1>
</div>

  <% @course_category.courses.each do |course| %>
    <div class="panel">
      <h5><%= link_to course.course_name, course %></h5>
    </div>
  <% end %>
<br>
<div class="clearfix">
  <%= link_to 'Delete category', @course_category,  class: "right button alert tiny radius", method: :delete, data: { confirm: 'Are you sure?' } %>
</div>