config/routes.rb
Rails.application.routes.draw do
  

  resources :roles

  devise_for :users
  root 'welcome#home'
  get 'welcome', to: 'welcome#index'
  get 'settings', to: 'settings#index'
  
  resources :employees

  resources :guardians

  resources :students
  
  resources :users
  
  resources :exam_categories
  
  resources :periods
  
  resources :groups do
    resources :attendances
    resources :attendance_registers
  end

  resources :courses do 
    resources :curriculums
    resources :chapters
    resources :lessons
    resources :exam_categories
    resources :exams do 
        resources :grades
    end
  end
  
  resources :course_categories

  
  

end

app/models/lesson.rb
class Lesson < ActiveRecord::Base
#   validates :lesson_title, :lesson_start_date, :lesson_end_date, presence: true
  belongs_to :chapter
  
  def to_param
    "#{id}-#{lesson_title.parameterize}"
  end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_filter :find_course
  before_action :set_lesson, only: [:show, :edit, :update, :destroy]

  # GET /lessons
  # GET /lessons.json
  def index
    @lessons = Lesson.all
  end

  # GET /lessons/1
  # GET /lessons/1.json
  def show
  end

  # GET /lessons/new
  def new
    @lesson = Lesson.new
  end

  # GET /lessons/1/edit
  def edit
  end

  # POST /lessons
  # POST /lessons.json
  def create
    @lesson = Lesson.new(lesson_params)

    respond_to do |format|
      if @lesson.save
        format.html { redirect_to [@course, @lesson], notice: 'Lesson was successfully created.' }
        format.json { render :show, status: :created, location: @lesson }
      else
        format.html { render :new }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lessons/1
  # PATCH/PUT /lessons/1.json
  def update
    respond_to do |format|
      if @lesson.update(lesson_params)
        format.html { redirect_to course_lesson_url, notice: 'Lesson was successfully updated.' }
        format.json { render :show, status: :ok, location: @lessons }
      else
        format.html { render :edit }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lessons/1
  # DELETE /lessons/1.json
  def destroy
    @lesson.destroy
    respond_to do |format|
      format.html { redirect_to course_lessons_url, notice: 'Lesson was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lesson
      @lesson = Lesson.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lesson_params
      params.require(:lesson).permit(:lesson_title, :lesson_description, :lesson_start_date, :lesson_end_date, :attachment, :chapter_id)
    end
  
  def find_course
    @course = Course.find(params[:course_id])
  end
  
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/views/lessons/_form.html.erb
<%= form_for [@course, @lesson] do |f| %>
  <% if @lesson.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@lesson.errors.count, "error") %> prohibited this lesson from being saved:</h2>

      <ul>
      <% @lesson.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :lesson_title %><br>
    <%= f.text_field :lesson_title %>
  </div>
  <div class="field">
    <%= f.label :lesson_description %><br>
    <%= f.text_area :lesson_description %>
  </div>
  <div class="field">
    <%= f.label :lesson_start_date %><br>
    <%= f.date_select :lesson_start_date %>
  </div>
  <div class="field">
    <%= f.label :lesson_end_date %><br>
    <%= f.date_select :lesson_end_date %>
  </div>
  <div class="field">
    <%= f.label :attachment %><br>
    <%= f.text_field :attachment %>
  </div>
  <div class="field">
    <%= f.label :chapter_id %><br>
    <%= f.text_field :chapter_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lessons/edit.html.erb
<h1>Editing Lesson</h1>

<%= render 'form' %>

<%= link_to 'Show', [@course, @lesson] %> |
<%= link_to 'Back', course_lessons_path %>

app/views/lessons/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Lessons</h1>

<table>
  <thead>
    <tr>
      <th>Lesson title</th>
      <th>Lesson description</th>
      <th>Lesson start date</th>
      <th>Lesson end date</th>
      <th>Attachment</th>
      <th>Chapter</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lessons.each do |lesson| %>
      <tr>
        <td><%= lesson.lesson_title %></td>
        <td><%= lesson.lesson_description %></td>
        <td><%= lesson.lesson_start_date %></td>
        <td><%= lesson.lesson_end_date %></td>
        <td><%= lesson.attachment %></td>
        <td><%= lesson.chapter %></td>
        <td><%= link_to 'Show', course_lesson_path(@course, lesson) %></td>
        <td><%= link_to 'Edit', edit_course_lesson_path(@course, lesson) %></td>
        <td><%= link_to 'Destroy', course_lesson_path(@course, lesson), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Lesson', new_course_lesson_path %>

app/views/lessons/new.html.erb
<h1>New Lesson</h1>

<%= render 'form' %>

<%= link_to 'Back', course_lessons_path %>

app/views/lessons/show.html.erb
<p>
  <strong>Lesson title:</strong>
  <%= @lesson.lesson_title %>
</p>

<p>
  <strong>Lesson description:</strong>
  <%= @lesson.lesson_description %>
</p>

<p>
  <strong>Lesson start date:</strong>
  <%= @lesson.lesson_start_date %>
</p>

<p>
  <strong>Lesson end date:</strong>
  <%= @lesson.lesson_end_date %>
</p>

<p>
  <strong>Attachment:</strong>
  <%= @lesson.attachment %>
</p>

<p>
  <strong>Chapter:</strong>
  <%= @lesson.chapter_id %>
</p>

<%= link_to 'Edit', edit_course_lesson_path(@course, @lesson) %> |
<%= link_to 'Back', course_lessons_path %>