config/routes.rb
Rails.application.routes.draw do
  

  resources :roles

  devise_for :users
  root 'welcome#home'
  get 'welcome', to: 'welcome#index'
  get 'settings', to: 'settings#index'
  
  resources :employees

  resources :guardians

  resources :students
  
  resources :users
  
  resources :exam_categories
  
  resources :periods
  
  resources :groups do
    resources :attendances
    resources :attendance_registers
  end

  resources :courses do 
    resources :curriculums
    resources :chapters
    resources :lessons
    resources :exam_categories
    resources :exams do 
        resources :grades
    end
  end
  
  resources :course_categories

  
  

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    
#     alias_action :create, :read, :update, :destroy, :to => :crud
    
    if user.role? :admin
      can :manage, :all
    elsif user.role? :teacher
      can :manage, [Chapter, Lesson, Attendance, Grade, Exam]
      can :read, Group
      can [:read, :update], [Student, Course]
      cannot [:create, :destroy], [Student, Course]
    else
      #       Temporary for now
      can :manage, :all
      #       Gotta sort the issue with role assignments first
#       can :read, [Course, Student, Group, Chapter, Lesson, Grade, Exam, Guardian]

  end
  end
end

app/models/attendance.rb
class Attendance < ActiveRecord::Base
  belongs_to :student
#   belongs_to :group
  belongs_to :attendance_register
  
  def show_status
    if status
      "Present"
    else
      "Absent"
    end
  end
  
end

app/models/chapter.rb
class Chapter < ActiveRecord::Base
  belongs_to :curriculum
  belongs_to :course
  has_many :lessons
    accepts_nested_attributes_for :lessons, allow_destroy: true,
  :reject_if => lambda { |attributes| attributes['lesson_title'].blank? }
  
  def with_blank_lessons(n = 1)
    n.times do
      lessons.build
    end
    self
  end
  
  def to_param
    "#{id}-#{chapter_title.parameterize}"
  end
  
end

app/models/course.rb
class Course < ActiveRecord::Base
  validates :course_name, :course_code, :group_id, :course_category_id, presence: true
  belongs_to :course_category
  belongs_to :group
#   delegate :students, to: :group
  has_many :exams
  has_many :chapters
  
  def students
    group.students
  end
  
  def to_param
    "#{id}-#{course_name.parameterize}"
  end
end

app/models/curriculum.rb
class Curriculum < ActiveRecord::Base
  has_many :chapters
  has_many :lessons
  accepts_nested_attributes_for :chapters, :lessons, allow_destroy: true,
                :reject_if => lambda { |attrs|
                                            attrs.all? { |key, value| value.blank? } 
                                          }

end

app/models/employee.rb
class Employee < ActiveRecord::Base
  has_many :courses
  has_many :groups
  has_many :students, :through => :groups
  
  def to_param
    "#{id}-#{last_name.parameterize}"
  end
end

app/models/exam.rb
class Exam < ActiveRecord::Base
  validates :title, :exam_date, :exam_category_id, presence: :true
  belongs_to :exam_category
  belongs_to :course
  has_many   :grades
  
  def to_param
    "#{id}-#{title.parameterize}"
  end
end

app/models/exam_category.rb
class ExamCategory < ActiveRecord::Base
  has_many :exams
  
  def to_param
    "#{id}-#{title.parameterize}"
  end
end

app/models/grade.rb
class Grade < ActiveRecord::Base
  belongs_to :student
#   validates :student, uniqueness: true
  belongs_to :exam
  validates_numericality_of :score
  
end

app/models/group.rb
class Group < ActiveRecord::Base
  validates :group_name, :group_code, presence: true, uniqueness: true
  
  has_many :students
  has_many :courses
  has_many :attendance_registers
  has_many :periods, through: :attendance_registers
  has_many :attendances, through: :attendance_registers
  
  def to_param
    "#{id}-#{group_name.parameterize}"
  end
end

app/models/guardian.rb
class Guardian < ActiveRecord::Base
  validates :last_name, :phone, presence: true
  validates :phone, uniqueness: true
  has_many :family_members
  has_many :students, :through => :family_members
  
  def full_name
    "#{last_name} #{first_name}".titleize
  end
  
  def to_param
    "#{id}-#{full_name.parameterize}"
  end
  
end

app/models/lesson.rb
class Lesson < ActiveRecord::Base
#   validates :lesson_title, :lesson_start_date, :lesson_end_date, presence: true
  belongs_to :chapter
  
  def to_param
    "#{id}-#{lesson_title.parameterize}"
  end
end

app/models/period.rb
class Period < ActiveRecord::Base
  has_many :attendance_registers
  validates :weekday, :start_time, :end_time, :period_title, presence: true
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users
  
end

app/models/student.rb
class Student < ActiveRecord::Base
  validates :first_name, :last_name, :username, :date_of_birth, :gender, :group_id, :enrollment_date, presence: true
  validates :username, uniqueness: true
 
  has_many :attendances
  belongs_to :group
  has_many :courses
#   delegate :courses, to: :group
#   has_many :exams, through: :courses
  has_many :grades #, through: :exams
  
  has_many :employees, through: :groups
  has_many :family_members
  has_many :guardians, through: :family_members
  accepts_nested_attributes_for :guardians,
            :reject_if => lambda { |attrs|
                              attrs.all? { |key, value| value.blank? } 
                            }
  
  def full_name
    "#{last_name} #{first_name}".titleize
  end
      
#   def courses
#     group.courses
#   end
  
  def with_blank_guardians(n = 1)
    n.times do
      guardians.build
    end
    self
  end
  
  def to_param
    "#{id}-#{full_name.parameterize}"
  end
  
end

app/models/user.rb
class User < ActiveRecord::Base
  before_save { self.email = email.downcase }
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :username, :email, :first_name, :last_name, presence: true 
  validates :username, :email, uniqueness: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  has_and_belongs_to_many :roles
  
  
  def full_name
    "#{last_name} #{first_name}".titleize
  end
  
  def role?(role)
    return !!self.roles.find_by_name(role.to_s.camelize)
  end
  
  def to_param
    "#{id}-#{full_name.parameterize}"
  end
  
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  load_and_authorize_resource

  # GET /courses
  # GET /courses.json
  def index
    @courses = Course.all
    @exams = Exam.all
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url, notice: 'Course was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def course_params
      params.require(:course).permit(:course_name, :course_code, :group_id, :course_category_id)
    end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/exams_helper.rb
module ExamsHelper
end

app/helpers/form_helper.rb
module FormHelper
  def setup_chapter(chapter)
    chapter.lessons ||= Lesson.new
    chapter.lessons.build
    chapter
  end
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/courses/_course_curriculum.html.erb
<h5>Curriculum 
  <span class="right">
    <%= link_to '<i class="fa fa-plus"></i>&nbsp; Add Chapter'.html_safe, new_course_chapter_path(@course, @chapter) %>
  </span>
</h5>
<br>

<% @course.chapters.each do |chapter| %>
<div class="panel clearfix">
  <h6>
    <%= link_to chapter.chapter_title, course_chapter_path(@course, chapter) %>
    <span class="right secondary-text">
      from: <%=chapter.chapter_start_date.to_time.strftime('%a %e %b %Y') %> - 
      to: <%= chapter.chapter_end_date.to_time.strftime('%a %e %b %Y') %></span>
  </h6>
<!--   <p class="right">
    <% if can? :update, @chapter %>
      <%#= link_to 'Edit', edit_course_chapter_path(@course, chapter) %> | 
    <% end %>
    <% if can? :destroy, @course %>
      <%#= link_to 'Remove', course_chapter_path(@course, chapter), method: :delete, data: { confirm: 'Are you sure?' } %>
    <% end %>
  </p> -->
</div>
<% end %>

app/views/courses/_course_students.html.erb
<table>
  <thead>
    <tr>
      <th>Names</th>
    </tr>
  </thead>

  <tbody>
    <% @course.group.students.each do |student|  %>
      <tr>
        <td><%= link_to student.full_name, student %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/courses/_course_tab.html.erb
<ul class="tabs" data-tab data-options="deep_linking:true">
<!--   <li class="tab-title active"><a href="#panel1"><i class="flaticon-home78"></i>&nbsp;<span class="hidden-for-small-only"> Overview</span></a></li> -->
  <li class="tab-title active">
    <%= link_to '<i class="flaticon-home78"></i>&nbsp; Overview'.html_safe, '#overview', tabindex: 1 %>
  </li>
  <li class="tab-title">
    <%= link_to '<i class="flaticon-people"></i>&nbsp; Students'.html_safe, '#students', tabindex: 2 %>
  </li>
  <li class="tab-title">
    <%= link_to '<i class="flaticon-applicattion"></i>&nbsp; Curriculum'.html_safe, '#curriculum', tabindex: 3 %>
  </li>
  <li class="tab-title">
    <%= link_to '<i class="flaticon-write12"></i>&nbsp; Exams'.html_safe, '#exam', tabindex: 4 %>
  </li>
</ul>

app/views/courses/_exam_tab.html.erb
<h5>Exams List 
  <span class="right">
    <%= link_to '<i class="fa fa-plus"></i>&nbsp; Add Exams'.html_safe, new_course_exam_path(@course, @exam) %> &nbsp; &nbsp;
    <%= link_to '<i class="flaticon-settings49"></i>&nbsp; Exams Categories'.html_safe, course_exam_categories_path(@course, @exam_categories) %>
  </span>
</h5>
<br>



<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Category</th>
      <th>Date</th>
      <th width="5%" colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% @course.exams.each do |exam| %>
      <tr>
        <td><%= link_to exam.title, [@course, exam] %></td>
        <td><%= exam.exam_category.title %></td>
        <td><%= exam.exam_date %></td>
        <td><%= link_to '', [@course, exam], method: :delete, data: { confirm: 'Are you sure?' }, class: 'fa fa-trash-o' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/courses/_form.html.erb
<%= form_for(@course) do |f| %>
  <% if @course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
      <% @course.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <fieldset>
    
      <div class="row">
        <div class="medium-6 columns">
          <%= f.label :course_name %>
          <%= f.text_field :course_name %>
        </div>
        <div class="medium-6 columns">
          <%= f.label :course_code %>
          <%= f.text_field :course_code %>
        </div>
      </div>
      <div class="row">
        <div class="medium-6 columns">
          <%= f.label :course_category_id %>
          <%= f.collection_select :course_category_id, CourseCategory.all, :id, :cc_name, {}, {class: "chosen-select", include_blank: true, multiple: false} %>
        </div>
        <div class="medium-6 columns">
          <%= f.label :group_id %>
          <%= f.collection_select :group_id, Group.all, :id, :group_name, {}, {class: "chosen-select", include_blank: true, multiple: false} %>
        </div>
      </div>
    
  </fieldset>

  <div class="actions">
    <%= f.submit class: "button success radius" %>
  </div>
<% end %>

app/views/courses/_overview.html.erb
<div class="medium-6 columns">
  <div class="panel">
    <h5>Course Overview</h5>
    <hr>
    <p>
      <strong>Course code:</strong>
      <%= @course.course_code %>
    </p>

    <p>
      <strong>Group:</strong>
      <%= link_to @course.group.group_name, @course.group %>
    </p>

    <p>
      <strong>Course category:</strong>
      <%= link_to @course.course_category.cc_name, @course.course_category %>
    </p>
    
    <p>
      <strong>Number of students:</strong>
      <%= @course.group.students.count %>
    </p>
  </div>
</div>

app/views/courses/edit.html.erb
<% provide(:title, 'Editing Course') %>

<div class="page-title">
  <h1>Editing Course</h1>
</div>

<%= render 'form' %>

<%= link_to 'Cancel', @course, class: 'button secondary tiny radius'  %> &nbsp; &nbsp;
<%= link_to 'Delete', @course, class: 'right button alert tiny radius', method: :delete, data: { confirm: 'Are you sure?' } %>

app/views/courses/index.html.erb
<% provide(:title, 'All Courses') %>

<div class="page-title">
  <h1>Courses</h1>
</div>

<%= link_to 'Create a new course', new_course_path, class: 'button tiny radius' %>
<br>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Class</th>
      <th width="10%" colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @courses.each do |course| %>
      <tr>
        <td><%= link_to course.course_name, course %></td>
        <td><%= link_to course.group.group_name, course.group %></td>
        <% if can? :update, @course %>
          <td><%= link_to '', edit_course_path(course), class: 'fa fa-pencil-square-o' %></td>
        <% end %>
        <% if can? :destroy, @student %>
          <td><%= link_to '', course, method: :delete, data: { confirm: 'Are you sure?' }, class: 'fa fa-trash-o' %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/courses/new.html.erb
<% provide(:title, 'New Course') %>

<div class="page-title">
  <h1>New Course</h1>
</div>

<%= render 'form' %>

<%= link_to 'Cancel', courses_path, class: 'button secondary tiny radius' %>

app/views/courses/show.html.erb
<% provide(:title, @course.course_name) %>

<div class="page-title clearfix">
  <h1><%= @course.course_name %> <span class="right"><%= link_to 'Edit', edit_course_path(@course) %>  | 
    <%= link_to 'View all courses', courses_path %></span></h1>
</div>

<%= render 'course_tab' %>

<div class="tabs-content">
  <div class="content active" id="overview">
    <%= render 'overview' %>
  </div>
  <div class="content" id="students">
    <%= render 'course_students' %>
  </div>
  <div class="content" id="curriculum">
    <%= render 'course_curriculum', locals: {variable: @chapters} %>
  </div>
  <div class="content" id="exam">
      <%= render 'exam_tab' %>
  </div>
</div>