config/routes.rb
Rails.application.routes.draw do
  

  resources :roles

  devise_for :users
  root 'welcome#home'
  get 'welcome', to: 'welcome#index'
  get 'settings', to: 'settings#index'
  
  resources :employees

  resources :guardians

  resources :students
  
  resources :users
  
  resources :exam_categories
  
  resources :periods
  
  resources :groups do
    resources :attendances
    resources :attendance_registers
  end

  resources :courses do 
    resources :curriculums
    resources :chapters
    resources :lessons
    resources :exam_categories
    resources :exams do 
        resources :grades
    end
  end
  
  resources :course_categories

  
  

end

app/models/exam.rb
class Exam < ActiveRecord::Base
  validates :title, :exam_date, :exam_category_id, presence: :true
  belongs_to :exam_category
  belongs_to :course
  has_many   :grades
  
  def to_param
    "#{id}-#{title.parameterize}"
  end
end

app/controllers/exams_controller.rb
class ExamsController < ApplicationController
  before_filter :find_course
  before_action :set_exam, only: [:show, :edit, :update, :destroy]

  # GET /exams
  # GET /exams.json
  def index
    @exams = find_course.exams.all
    @grade = find_course.exams.grades.new
  end

  # GET /exams/1
  # GET /exams/1.json
  def show
  end

  # GET /exams/new
  def new
    @exam = Exam.new
  end

  # GET /exams/1/edit
  def edit
  end

  # POST /exams
  # POST /exams.json
  def create
    @exam = find_course.exams.new(exam_params)

    respond_to do |format|
      if @exam.save
        format.html { redirect_to [@course, @exam], notice: 'Exam was successfully created.' }
        format.json { render :show, status: :created, location: @exam }
      else
        format.html { render :new }
        format.json { render json: @exam.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /exams/1
  # PATCH/PUT /exams/1.json
  def update
    respond_to do |format|
      if @exam.update(exam_params)
        format.html { redirect_to [@course, @exam], notice: 'Exam was successfully updated.' }
        format.json { render :show, status: :ok, location: @exam }
      else
        format.html { render :edit }
        format.json { render json: @exam.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /exams/1
  # DELETE /exams/1.json
  def destroy
    @exam.destroy
    respond_to do |format|
      format.html { redirect_to course_exams_url, notice: 'Exam was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_exam
#       @exam = find_course.exams.find(params[:id])
      @exam = Exam.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def exam_params
      params.require(:exam).permit(:title, :description, :exam_date, :exam_category_id, :course_id)
    end
  
    def find_course
      @course = Course.find(params[:course_id])
    end
end

app/helpers/exams_helper.rb
module ExamsHelper
end

app/views/exams/_exam_details.html.erb
<div class="panel">

  <p><strong>Description:</strong><br>
    <%= @exam.description %>
  </p>

  <p>
    <strong>Exam date:</strong>
    <%= @exam.exam_date %>
  </p>

  <p>
    <strong>Exam category:</strong>
    <%= @exam.exam_category.title %>
  </p>
  
  <p>
    <strong>Course:</strong>
    <%=@exam.course.course_name %>
  </p>

  <p>
    <strong>Group:</strong>
    <%= @exam.course.group.group_name %>
  </p>

</div>

<%= link_to 'Edit', edit_course_exam_path, class: 'button success tiny radius' %>

app/views/exams/_exam_grades.html.erb
<h5>
  <%= link_to '<i class="fa fa-plus"></i>&nbsp; Add Grade'.html_safe, new_course_exam_grade_path(@course, @exam, :grade) %>
</h5>

<br>
<table>
  <thead>
    <tr>
      <th>Student</th>
      <th>Scores</th>
      <th>Feedback</th>
    </tr>
  </thead>

  <tbody>
    <% @exam.grades.collect do |grade| %>
      <tr>
        <td><%= grade.student.full_name %></td>
        <td><%= best_in_place grade, :score, :path => [@course, @exam, grade] %></td>
        <td><%= best_in_place grade, :feedback, :path => [@course, @exam, grade], :as => :input, :nil => "Add feedback" %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<br>
<div class="panel callout radius">
  <p>List of all students who should graded </p>
  <% @course.group.students.each do |student|  %>
    <p>
      <strong> > <%= link_to student.full_name, student %></strong>
    </p>
  <% end %>
</div>

app/views/exams/_exams.html.erb
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Category</th>
      <th>Date</th>
    </tr>
  </thead>

  <tbody>
    <% @exams.each do |exam| %>
      <tr>
        <td><%= link_to exam.title, [@course, exam] %></td>
        <td><%= link_to exam.exam_category.title, [@course, @exam_category] %></td>
        <td><%= exam.exam_date %></td>
        <td><%= link_to 'Delete', [@course, exam], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/exams/_exams_tab.html.erb
<ul class="tabs" data-tab data-options="deep_linking:true">
  <li class="tab-title active"><a href="#grades"><i class="flaticon-people"></i>&nbsp;<span class="hidden-for-small-only"> Grades</span></a></li>
  <li class="tab-title"><a href="#details"><i class="flaticon-home78"></i>&nbsp;<span class="hidden-for-small-only"> Details</span></a></li>
</ul>

app/views/exams/_form.html.erb
<%= form_for [@course, @exam] do |f| %>
  <% if @exam.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@exam.errors.count, "error") %> prohibited this exam from being saved:</h2>

      <ul>
      <% @exam.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<fieldset>
  <div class="row">
    <div class="medium-6 columns">
      <div class="field">
        <%= f.label :title %>
        <%= f.text_field :title %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="large-12 columns">
      <div class="field">
        <%= f.label :description %>
        <%= f.text_area :description %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="medium-6 columns">
      <div class="field">
        <%= f.label :exam_date %>
        <%= f.text_field :exam_date, class: 'datepicker' %>
      </div>
    </div>
    <div class="medium-6 columns">
      <div class="field">
        <%= f.label :exam_category_id %>
        <%= f.collection_select :exam_category_id, ExamCategory.all, :id, :title, {}, {class: "chosen-select", include_blank: true, multiple: false} %>
      </div>
    </div>
  </div>
</fieldset>
  <div class="actions">
    <%= f.submit class: 'button success tiny radius' %>
  </div>
<% end %>

app/views/exams/edit.html.erb
<% provide(:title, 'Editing Exam') %>

<div class="page-title">
  <h1>Editing Exam</h1>
</div>

<%= render 'form' %>

<%= link_to 'Cancel', course_exam_path, class: 'button secondary tiny radius' %>
<%= link_to 'Delete Exam', course_exam_url, class: 'right button alert tiny radius', method: :delete, data: { confirm: 'Are you sure?' } %>

app/views/exams/index.html.erb
<% provide(:title, 'Editing Exam') %>

<br>
<h5>Exams List 
  <span class="right">
    <%= link_to 'Add Exam', new_course_exam_path %> | 
    <%= link_to 'Back', course_path(@course) %>
  </span>
</h5>
<br>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Category</th>
      <th>Date</th>
    </tr>
  </thead>

  <tbody>
    <% @exams.each do |exam| %>
      <tr>
        <td><%= link_to exam.title, [@course, exam] %></td>
        <td><%= link_to exam.exam_category.title, [@course, @exam_category] %></td>
        <td><%= exam.exam_date %></td>
        <td><%= link_to 'Delete', [@course, exam], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/exams/new.html.erb
<h5>New Exam</h5>

<%= render 'form' %>

<%= link_to 'Back', course_path(@course, :anchor => 'exam') %>

app/views/exams/show.html.erb
<% provide(:title, @exam.title) %>

<br>
<h5><%= @exam.title %> - <%= @exam.exam_category.title %> <span class="right"><%= link_to '<i class="fa fa-arrow-left"></i>&nbsp; Back'.html_safe, course_path(@course, :anchor => 'exam') %></span></h5>
<br>

<%= render 'exams_tab' %>

<div class="tabs-content">
  <div class="content active" id="grades">
    <%= render 'exam_grades' %>
  </div>
    <div class="content" id="details">
    <%= render 'exam_details' %>
  </div>
</div>